name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  setup-ssh:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install SSH client
        run: sudo apt-get install -y openssh-client

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Debug SSH key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | head -n 10
          echo "SSH Key length: $(echo "${{ secrets.SSH_PRIVATE_KEY }}" | wc -c)"
          ls -la ~/.ssh
          cat ~/.ssh/id_rsa

      - name: Add SSH key to agent
        run: |
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_rsa

      - name: Test SSH connection
        run: ssh -o StrictHostKeyChecking=no -T git@github.com || true

  setup-tunnel:
    runs-on: ubuntu-latest
    needs: setup-ssh  # This job depends on setup-ssh job

    steps:
      - name: Set up SSH tunnel to EC2 through bastion host
        run: |
          ssh -o StrictHostKeyChecking=no -v -fNT -L 2222:10.0.0.47:22 ubuntu@3.110.43.35
          sleep 5

  deploy:
    runs-on: ubuntu-latest
    needs: setup-tunnel  # This job depends on setup-tunnel job

    steps:
      - name: Deploy to private EC2 instance
        run: |
          ssh -o StrictHostKeyChecking=no -p 2222 ubuntu@localhost << 'EOF'
            # Deployment commands here
            cd /var/www/html/react-frontend/
            git pull
            npm i
            npm run build
            # Additional deployment commands
            echo "Deployment completed on $(whoami)"
            # Restart services if needed
            sudo systemctl restart nginx
          EOF
